spring:
  datasource:
    url: jdbc:mysql://localhost:3306/recipe
    username: recipe_user
    password: test@20
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true